blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/pocket-db/pocket/discussions/categories/q-a
    about: Ask questions and get help from the community in GitHub Discussions
  - name: Ideas & Feature Discussions
    url: https://github.com/pocket-db/pocket/discussions/categories/ideas
    about: Share ideas and discuss potential features before opening a feature request
  - name: Show and Tell
    url: https://github.com/pocket-db/pocket/discussions/categories/show-and-tell
    about: Share projects and applications you've built with Pocket
